name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        submodules: true  # Fetch Hugo themes
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Clean docs
      run: rm -rf docs

    - name: Build Hugo in docs
      run: cd hugo; hugo -d ../docs; touch ../docs/.nojekyll

    - name: Git Push Hugo docs
      run: git config user.name "powdrsoft"; git config user.email "info@powdrsoft.com"; git add docs; git commit -m "hugo docs"; git push

    - name: Get dependencies
      run: |
        go get github.com/samfoo/mdcat
        #go get github.com/isacikgoz/tldr/cmd/tldr
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build uh
      run: make build

    - name: Test
      run: make test
